name: Rust

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tk-voice-mac
        path: |
          dist/
        retention-days: 3
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      
